{- This is a kubedeploy/jinja2 template.
   This jinja2-comment avoids deployment without processing the template first.
   It will be removed by kubedeploy tool. -}

# Traefik-Endpoint for Rancher Server which is running at one of the nodes at https/8443

---

kind: Service
apiVersion: v1
metadata:
  name: external-rancher-server
  namespace: kube-system
spec:
  type: ExternalName
  externalName: {{ RANCHER_SERVER_DOMAIN }}
  ports:
  - name: rancher
    port: {{ RANCHER_SERVER_PORT|default(8443) }}
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: rancher-server
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefix
    ingress.kubernetes.io/protocol: {{ RANCHER_SERVER_PROTOCOL|default('https') }}
spec:
  rules:
  - host: {{ RANCHER_SERVER_DOMAIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: external-rancher-server
          servicePort: rancher
